In [ ]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\DELL\Desktop\MATHS PROJECTS\PR-5\combined_employee_dataset_1.csv")
df

,age,years_experience,education_level,department,performance_score,performance_category
0,58,23,High School,Finance,10,Excellent
1,48,39,Bachelor,HR,6,Good
2,34,15,High School,HR,5,Average
3,27,29,PhD,HR,4,Average
4,40,36,PhD,Finance,2,Poor
...,...,...,...,...,...,...
786,21,19,Bachelor,Sales,9,Very Good
787,25,4,Master,Finance,4,Average
788,47,35,Bachelor,Finance,6,Good
789,47,17,High School,Sales,1,Poor
790,39,28,Bachelor,Sales,9,Very Good

In [5]:
employee1 = df.loc[0, ['age','years_experience','performance_score']].values
employee2 = df.loc[1, ['age','years_experience','performance_score']].values

print("Employee 1 Vector :", employee1)
print("Employee 2 Vector :", employee2)

Employee 1 Vector : [np.int64(58) np.int64(23) np.int64(10)]
Employee 2 Vector : [np.int64(48) np.int64(39) np.int64(6)]

In [6]:
norm1 = np.linalg.norm(employee1, ord=1)

print("Norm-1 :", norm1)

Norm-1 : 91

In [7]:
norm2 = np.linalg.norm(employee1)

print("Norm-2 :", norm2)

Norm-2 : 63.190189111918315

In [8]:

dot_product = np.dot(employee1, employee2)

print("Dot Product :", dot_product)

Dot Product : 3741

In [9]:

cos_theta = np.dot(employee1, employee2) / (np.linalg.norm(employee1) * np.linalg.norm(employee2))

angle = np.degrees(np.arccos(cos_theta))

print("Angle Between Vectors :", angle)

Angle Between Vectors : 17.679505521863163

In [11]:

employee1 = df.loc[0, ['age','years_experience','performance_score']].values
employee2 = df.loc[1, ['age','years_experience','performance_score']].values

v1 = employee1[:3]
v2 = employee2[:3]

cross_product = np.cross(v1, v2)

print("Cross Product :", cross_product)

Cross Product : [np.int64(-252) np.int64(132) np.int64(1158)]

In [12]:

projection = (np.dot(employee1, employee2) / np.dot(employee2, employee2)) * employee2

print("Projection :", projection)

Projection : [np.float64(46.50815850815851) np.float64(37.78787878787879)
 np.float64(5.813519813519814)]

In [13]:
A = df[['age','years_experience','performance_score']].head(5).values

print(A)

[[58 23 10]
 [48 39  6]
 [34 15  5]
 [27 29  4]
 [40 36  2]]

In [14]:
B = np.array([
    [1,2,3],
    [5,4,3],
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

addition = A + B

print(addition)

[[59 25 13]
 [53 43  9]
 [35 16  6]
 [29 31  6]
 [43 39  5]]

In [18]:
B = np.array([
    [1,2,3,4],
    [5,4,3,2],
    [1,1,1,1]
])

multiplication = np.matmul(A, B)

print(multiplication)

[[183 218 253 288]
 [249 258 267 276]
 [114 133 152 171]
 [176 174 172 170]
 [222 226 230 234]]

In [19]:

transpose = A.T


print(transpose)

[[58 48 34 27 40]
 [23 39 15 29 36]
 [10  6  5  4  2]]

In [20]:
A = df[['age','years_experience','performance_score']].head(3).values

determinant = np.linalg.det(A)

print("Determinant :", determinant)

Determinant : -797.9999999999995

In [21]:

inverse = np.linalg.inv(A)

print(inverse)

[[-0.13157895 -0.04385965  0.31578947]
 [ 0.04511278  0.06265664 -0.16541353]
 [ 0.7593985   0.11027569 -1.45112782]]

In [22]:

transformation_matrix = np.array([
    [1,0],
    [0,2]
])

points = np.array([
    [2,3],
    [4,5]
])

transformed_points = np.dot(points, transformation_matrix)

print(transformed_points)

[[ 2  6]
 [ 4 10]]

In [23]:

cov_matrix = np.cov(A.T)

print(cov_matrix)

[[145.33333333  61.33333333  29.        ]
 [ 61.33333333 149.33333333   0.        ]
 [ 29.           0.           7.        ]]

In [24]:

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues :")
print(eigenvalues)

print("\nEigenvectors :")
print(eigenvectors)

Eigenvalues :
[ 2.10730699e+02  9.09359674e+01 -3.72153363e-16]

Eigenvectors :
[[-0.7039152  -0.67078598 -0.23355849]
 [-0.70318107  0.7045102   0.09592581]
 [-0.10019865 -0.23175754  0.96759944]]

In [25]:

from scipy.linalg import lu

P, L, U = lu(A)

print("P Matrix :")
print(P)

P Matrix :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [26]:

U, S, VT = np.linalg.svd(A)

print("U Matrix :")
print(U)

print("\nSingular Values :")
print(S)

print("\nVT Matrix :")
print(VT)

U Matrix :
[[-0.65789852  0.59839597 -0.45726557]
 [-0.64291995 -0.76246739 -0.07278336]
 [-0.39220335  0.2461011   0.88634687]]

Singular Values :
[95.18352967 14.13307426  0.59320451]

VT Matrix :
[[-0.86520416 -0.48420766 -0.1302486 ]
 [ 0.45821372 -0.86899738  0.18677188]
 [ 0.20362207 -0.10191411 -0.97373075]]

In [27]:
from sklearn.decomposition import PCA

X = df[['age','years_experience','performance_score']]

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X)

print(pca_result)

[[17.82280057 -3.91524678]
 [13.48300643 14.40127993]
 [-7.49793903 -3.8288385 ]
 ...
 [11.24939913 10.93599121]
 [ 5.43569988 -6.1665846 ]
 [ 1.43681116  6.91913229]]

In [28]:

pca_df = pd.DataFrame(pca_result, columns=['PC1','PC2'])

pca_df.head()

         PC1        PC2
0  17.822801  -3.915247
1  13.483006  14.401280
2  -7.497939  -3.828839
3  -9.626696  11.665603
4   4.924696  14.086029

In [30]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X = df[['age','years_experience','performance_score']]

y = df['department']

lda = LinearDiscriminantAnalysis(n_components=1)

lda_result = lda.fit_transform(X, y)

print(lda_result)

[[-1.00420598e+00]
 [-1.41149857e+00]
 [ 5.41861116e-01]
 [-2.67518672e-01]
 [-4.54314913e-01]
 [ 7.91469188e-01]
 [-1.59201582e+00]
 [ 1.99144487e-01]
 [ 4.07281138e-01]
 [-1.27889202e+00]
 [ 2.16820710e+00]
 [ 5.89451122e-01]
 [-4.72719677e-01]
 [-2.44525530e-01]
 [-3.19117930e-01]
 [-9.19806447e-01]
 [ 1.40749092e+00]
 [ 2.92622757e-01]
 [-4.65412212e-02]
 [-1.79724133e+00]
 [-1.79541982e-01]
 [ 1.89146074e+00]
 [ 3.37116713e-01]
 [ 1.41154919e+00]
 [ 1.74411347e+00]
 [-1.22016296e+00]
 [ 1.51234217e+00]
 [ 1.72309377e+00]
 [ 3.89332975e-01]
 [ 4.37539985e-01]
 [-1.90356040e+00]
 [-2.87046052e-01]
 [ 2.75291599e-01]
 [ 1.06058013e+00]
 [-3.07954366e-01]
 [-1.11629843e+00]
 [ 5.99603464e-01]
 [-1.03185458e-01]
 [-1.75731125e+00]
 [ 5.87477688e-01]
 [ 5.30697552e-01]
 [-1.97420593e+00]
 [ 9.74663768e-01]
 [ 1.82239442e+00]
 [ 7.23525489e-01]
 [-7.29457555e-01]
 [ 1.65308484e-01]
 [-2.00184983e+00]
 [-6.81410949e-01]
 [-2.25615155e-01]
 [ 9.50140419e-01]
 [ 3.55570487e-01]
 [ 7.97242565e-01]
 [-2.11725254e-01]
 [-1.37303631e+00]
 [ 1.40393827e+00]
 [-1.62273127e+00]
 [ 1.32616294e+00]
 [ 8.04278440e-02]
 [-1.97922242e-01]
 [-7.43853067e-01]
 [ 5.44315657e-01]
 [ 1.62441011e+00]
 [-6.98853501e-01]
 [ 1.72825014e+00]
 [ 7.74594631e-01]
 [ 4.75385241e-01]
 [-9.19973892e-02]
 [-1.19150783e+00]
 [ 9.56259004e-01]
 [ 1.90422802e+00]
 [ 1.02409764e-01]
 [-8.53811677e-01]
 [ 6.57530719e-01]
 [ 5.08555229e-01]
 [-1.73223328e+00]
 [ 9.69507395e-01]
 [ 5.07544007e-01]
 [ 1.55584941e+00]
 [-4.38315679e-01]
 [ 2.05516593e-02]
 [-3.54027539e-01]
 [ 1.87816334e+00]
 [-5.56070110e-01]
 [-1.93328913e+00]
 [ 6.95832576e-01]
 [ 8.29450342e-01]
 [ 4.93814510e-01]
 [-2.78312524e-01]
 [ 1.17150484e-01]
 [-9.85776712e-01]
 [-5.81629185e-01]
 [-6.13923851e-01]
 [-5.82727296e-01]
 [ 4.27338634e-01]
 [ 6.67201955e-01]
 [-2.30154523e-01]
 [ 1.66791735e+00]
 [ 1.49343180e+00]
 [ 3.44888029e-01]
 [ 5.22469635e-01]
 [-1.43091455e+00]
 [-7.52056480e-01]
 [ 1.80102301e-02]
 [-1.87293184e+00]
 [-1.26289993e-01]
 [-4.62382427e-01]
 [ 1.34608453e+00]
 [ 5.82272306e-01]
 [-5.26909373e-01]
 [-2.87046052e-01]
 [-8.20505790e-01]
 [-2.79760536e-02]
 [ 1.94580614e-01]
 [-2.26120766e-01]
 [-1.33014607e+00]
 [-1.73855494e-01]
 [-1.51176144e+00]
 [-1.11162316e+00]
 [-1.59866452e+00]
 [ 3.57630810e-01]
 [-1.36331606e+00]
 [ 8.28808832e-01]
 [ 3.31590628e-01]
 [ 1.42743703e+00]
 [-1.15366258e+00]
 [ 7.75605853e-01]
 [-1.47639523e+00]
 [-8.64958089e-02]
 [ 1.08875415e+00]
 [-1.78506256e-01]
 [-2.94656965e-01]
 [ 1.40751543e+00]
 [ 8.11958780e-01]
 [ 5.20841409e-01]
 [-1.11629843e+00]
 [ 9.27628383e-01]
 [-2.44044424e-01]
 [-1.35621076e+00]
 [ 8.74882005e-01]
 [ 2.06129553e+00]
 [ 1.30305840e+00]
 [-1.14620819e-01]
 [ 3.29986906e-01]
 [ 1.80666209e-01]
 [-1.35004316e+00]
 [-6.79326121e-01]
 [-2.12342259e-01]
 [ 5.35742531e-01]
 [ 4.09788672e-02]
 [-1.10697240e+00]
 [ 1.81932288e+00]
 [ 2.21270106e+00]
 [ 7.67489329e-01]
 [ 1.42078833e+00]
 [-1.97113438e+00]
 [-1.25848932e+00]
 [ 1.65095591e+00]
 [-1.79921476e+00]
 [ 9.69507395e-01]
 [ 6.85631224e-01]
 [ 8.02793155e-01]
 [ 2.05744178e-01]
 [ 4.11339400e-01]
 [-9.17240513e-01]
 [-1.81096695e-01]
 [ 1.35834621e+00]
 [ 1.43871198e+00]
 [-1.71994710e+00]
 [-1.47233696e+00]
 [-1.58497770e-01]
 [-1.11373249e+00]
 [-6.76735682e-01]
 [-7.37204367e-01]
 [-7.56595848e-01]
 [-2.64447127e-01]
 [-1.90199935e-01]
 [-4.52181075e-01]
 [ 1.84082369e+00]
 [-5.48940303e-01]
 [ 9.42369103e-01]
 [-1.94506970e+00]
 [-3.64734501e-01]
 [ 1.73340651e+00]
 [-7.28976449e-01]
 [ 6.47785969e-01]
 [ 6.03180620e-01]
 [-7.23289961e-01]
 [ 8.33989710e-01]
 [ 1.06060464e+00]
 [ 1.24382372e+00]
 [ 1.04928067e+00]
 [-7.53548808e-01]
 [-7.06773958e-03]
 [-8.58351045e-01]
 [ 5.95545202e-01]
 [ 1.79062487e-01]
 [-2.03712915e+00]
 [-1.91029599e+00]
 [ 1.33149717e-01]
 [-1.04306246e+00]
 [-1.04920555e+00]
 [-1.03545154e+00]
 [-4.61901321e-01]
 [ 1.45275494e-01]
 [-1.69486913e+00]
 [-2.16881627e-01]
 [ 2.57899167e-03]
 [ 6.95375974e-01]
 [ 9.94079754e-01]
 [ 1.71190570e+00]
 [-7.49490546e-01]
 [-9.65612620e-02]
 [-5.53479671e-01]
 [-1.46309782e+00]
 [-8.13881594e-01]
 [ 6.47810474e-01]
 [-3.42246970e-01]
 [-2.00184983e+00]
 [-7.05958803e-01]
 [-1.65257864e-01]
 [-9.39728044e-01]
 [-6.16514290e-01]
 [-1.15464929e+00]
 [ 6.70754606e-01]
 [-1.56130037e+00]
 [-1.92790374e-01]
 [-3.89306860e-01]
 [ 1.70725494e+00]
 [-4.46037986e-01]
 [-5.62188695e-01]
 [-6.39988538e-01]
 [ 4.44694297e-01]
 [-5.26909373e-01]
 [-1.47746883e+00]
 [ 7.31593003e-01]
 [-4.30199155e-01]
 [ 1.23917296e+00]
 [-1.17603871e+00]
 [ 7.02024675e-01]
 [ 3.96968393e-01]
 [ 5.79706372e-01]
 [-1.43595953e+00]
 [ 1.19673933e+00]
 [-2.05397921e+00]
 [-1.43757050e-01]
 [-9.64781509e-01]
 [-4.37464860e-01]
 [-3.73265866e-02]
 [-2.67999778e-01]
 [ 1.22328512e+00]
 [ 5.81815704e-01]
 [-1.54396921e+00]
 [ 9.03512626e-01]
 [ 1.85767374e+00]
 [ 7.78619101e-02]
 [-2.98690722e-01]
 [ 6.47785969e-01]
 [ 5.33152093e-01]
 [ 7.62336837e-02]
 [-3.77958388e-01]
 [ 6.75001553e-02]
 [-1.36590650e+00]
 [ 1.25760223e+00]
 [-7.48984935e-01]
 [-7.45296386e-01]
 [ 7.00877555e-01]
 [-1.54945119e-01]
 [-1.63654142e-01]
 [-3.03398243e-03]
 [ 1.05198250e+00]
 [ 3.90455591e-01]
 [-1.44320073e+00]
 [-6.17501007e-01]
 [ 4.94320120e-01]
 [ 8.59067679e-01]
 [-1.89335905e+00]
 [ 9.37348628e-01]
 [ 1.51848526e+00]
 [-4.00100711e-01]
 [-1.13264287e+00]
 [-8.57894444e-01]
 [ 6.11914148e-01]
 [ 1.55131637e-01]
 [-6.82397666e-01]
 [ 7.16740890e-01]
 [ 6.04278730e-01]
 [ 4.53859922e-01]
 [-6.11839023e-01]
 [-4.12275497e-01]
 [-3.96548060e-01]
 [-8.44091432e-01]
 [-2.41935092e-01]
 [ 1.33278713e+00]
 [-1.01392844e-02]
 [ 2.03672317e+00]
 [ 9.86998957e-01]
 [-1.71479072e+00]
 [-4.00100711e-01]
 [-1.39587395e-01]
 [ 1.40960026e+00]
 [-4.93097875e-01]
 [-1.37464003e+00]
 [ 1.48221922e+00]
 [ 4.34925042e-01]
 [-3.28949569e-01]
 [ 2.09914079e+00]
 [ 8.69750137e-01]
 [ 4.12326117e-01]
 [ 1.13063317e+00]
 [-1.89741731e+00]
 [-1.54439508e-01]
 [-4.28138832e-01]
 [ 7.59261412e-01]
 [-9.00484599e-02]
 [ 2.00708133e+00]
 [-7.71472466e-01]
 [ 1.83417499e+00]
 [ 2.33412587e-01]
 [-4.31666978e-01]
 [-3.22300868e-01]
 [-6.37398099e-01]
 [-7.55497737e-01]
 [-7.10658574e-01]
 [-1.48253831e+00]
 [-2.40972879e-01]
 [-3.48871166e-01]
 [-3.32045619e-01]
 [-9.05295661e-02]
 [ 2.04781966e-01]
 [ 2.00708133e+00]
 [-1.69230319e+00]
 [-1.40890813e+00]
 [-7.54535525e-01]
 [ 5.29093831e-01]
 [ 5.46906095e-01]
 [-1.48913423e-01]
 [ 2.08071152e+00]
 [ 2.50719240e-01]
 [-8.42031109e-01]
 [-5.18681456e-01]
 [-8.25156552e-01]
 [ 1.10926825e+00]
 [-1.69316126e-01]
 [ 1.31289004e+00]
 [-2.39369158e-01]
 [-1.67206793e-01]
 [-1.04925078e-01]
 [ 1.61409737e+00]
 [-1.39614084e+00]
 [-1.32645752e+00]
 [ 2.63992136e-01]
 [-8.60965989e-01]
 [ 5.09036335e-01]
 [-5.11551649e-01]
 [ 1.33168902e+00]
 [ 1.33794350e+00]
 [-1.70766092e+00]
 [ 8.42081729e-01]
 [ 1.74005521e+00]
 [ 8.46275889e-01]
 [ 2.59958379e-01]
 [ 3.99921502e-02]
 [ 1.43454233e+00]
 [-3.96412162e-01]
 [ 1.25805883e+00]
 [-7.17171376e-01]
 [-5.38233341e-01]
 [ 9.67077360e-01]
 [-3.44812904e-01]
 [ 6.99385227e-01]
 [-5.73969263e-01]
 [ 1.69366746e-01]
 [ 6.07831381e-01]
 [ 7.22378369e-01]
 [ 1.55227225e+00]
 [ 1.09743867e+00]
 [-5.41810496e-01]
 [-8.95739699e-01]
 [ 1.74766612e+00]
 [ 1.76045791e+00]
 [-1.34392458e+00]
 [ 1.71497724e+00]
 [ 1.30872038e+00]
 [ 3.47867680e-02]
 [-1.08349815e+00]
 [-1.32349737e+00]
 [ 3.48357775e-02]
 [ 1.07802269e+00]
 [-1.39552384e+00]
 [-6.14293563e-01]
 [ 7.89471249e-01]
 [ 7.47456338e-01]
 [ 3.11052026e-01]
 [-6.43541189e-01]
 [-1.46163000e+00]
 [ 3.00850675e-01]
 [-4.57843059e-01]
 [ 4.40611530e-01]
 [ 1.42532769e+00]
 [ 8.35593431e-01]
 [ 1.21519310e+00]
 [-4.67587809e-01]
 [-1.24620314e+00]
 [-6.14404957e-01]
 [ 9.96213591e-01]
 [ 2.87602283e-01]
 [-1.91485986e+00]
 [ 1.23559581e+00]
 [ 3.61207966e-01]
 [-1.40685505e-01]
 [ 2.08071152e+00]
 [ 2.21126407e-01]
 [ 3.28494578e-01]
 [ 7.97106667e-01]
 [-1.55774772e+00]
 [-4.81822918e-01]
 [-3.16663390e-01]
 [ 8.36050033e-01]
 [-3.74430242e-01]
 [ 1.05654638e+00]
 [-5.27920595e-01]
 [ 8.98997762e-01]
 [ 1.31692380e+00]
 [ 5.01935017e-02]
 [-1.20833338e+00]
 [-6.65042003e-01]
 [ 8.55947125e-01]
 [-1.62126344e+00]
 [-1.01296401e+00]
 [-3.73949136e-01]
 [-1.63678647e-01]
 [-8.44621547e-01]
 [ 5.11121163e-01]
 [ 1.38133935e+00]
 [ 1.92414962e+00]
 [-9.97606290e-01]
 [-6.77352687e-01]
 [-1.57516577e+00]
 [ 1.37826780e+00]
 [ 5.34619916e-01]
 [-1.06408217e+00]
 [ 1.15683375e+00]
 [ 1.38085824e+00]
 [ 1.37837920e+00]
 [ 4.08292360e-01]
 [-3.54003034e-01]
 [-2.43402915e-01]
 [ 2.05366011e+00]
 [-3.52929428e-01]
 [-2.95668187e-01]
 [-1.78530761e-01]
 [-7.11003781e-01]
 [-3.60146124e-01]
 [ 1.84267869e-01]
 [-1.66269086e-01]
 [-1.65186750e+00]
 [-1.29376864e+00]
 [-1.43705764e+00]
 [ 1.48061550e+00]
 [ 1.89244745e+00]
 [ 1.83617293e+00]
 [-9.26388986e-02]
 [ 2.20139690e-01]
 [-1.05129038e+00]
 [ 1.15571114e+00]
 [ 1.75046192e-02]
 [-1.04416057e+00]
 [ 7.63455572e-01]
 [-1.12294713e+00]
 [-2.78793630e-01]
 [ 5.82777916e-01]
 [-1.19911875e+00]
 [ 1.76151345e-01]
 [ 4.75785583e-02]
 [-6.49684278e-01]
 [ 9.42480496e-01]
 [-4.03060863e-01]
 [-3.31540008e-01]
 [ 1.07903391e+00]
 [ 4.24772700e-01]
 [ 9.63388810e-01]
 [-1.17198045e+00]
 [-1.19201344e+00]
 [ 3.26915361e-01]
 [ 7.51514600e-01]
 [-1.02832174e+00]
 [ 2.29354325e-01]
 [-1.26107976e+00]
 [ 8.55842167e-02]
 [-4.28619938e-01]
 [-9.74613148e-01]
 [-1.76849931e+00]
 [-1.13058255e+00]
 [ 2.88589000e-01]
 [-1.88721596e+00]
 [-9.31105909e-01]
 [-6.99815713e-01]
 [ 4.74262625e-01]
 [-1.40068021e+00]
 [-1.09738805e+00]
 [ 3.47959574e-01]
 [-2.36754214e-01]
 [ 6.90170592e-01]
 [-1.14848170e+00]
 [-8.60965989e-01]
 [-1.39859538e+00]
 [ 8.67159698e-01]
 [-4.02069946e-03]
 [ 5.76610322e-01]
 [ 4.34925042e-01]
 [ 6.46206752e-01]
 [ 4.07786749e-01]
 [-6.82509059e-01]
 [-1.89188714e-01]
 [ 1.98021872e-01]
 [ 2.64128035e-01]
 [ 1.14145152e+00]
 [ 1.87509179e+00]
 [-7.87816907e-01]
 [ 2.46344259e-02]
 [-2.26601872e-01]
 [ 2.20439872e-02]
 [ 1.04065854e+00]
 [ 9.17427031e-01]
 [-1.44418745e+00]
 [ 5.08579734e-01]
 [-3.86210810e-01]
 [ 1.39749408e-01]
 [-1.56854157e+00]
 [ 7.08599861e-01]
 [-4.47024703e-01]
 [-9.98111901e-01]
 [-1.01346962e+00]
 [ 9.16810027e-01]
 [-2.35816507e-01]
 [ 1.46993304e+00]
 [-1.87769900e-01]
 [ 4.58904901e-01]
 [-1.14740809e+00]
 [-8.01923160e-02]
 [ 7.98093384e-01]
 [ 7.45988515e-01]
 [ 2.24703563e-01]
 [ 2.23211235e-01]
 [-1.51849069e-01]
 [-4.16469657e-01]
 [ 1.78294545e+00]
 [-5.48852264e-03]
 [ 3.82252178e-01]
 [-1.29582896e+00]
 [ 6.89738496e-01]
 [ 8.95926217e-01]
 [-1.86758678e-01]
 [-6.44071304e-01]
 [-5.67875183e-01]
 [ 2.13379596e-01]
 [ 1.37420954e+00]
 [ 1.34816936e+00]
 [ 5.24899670e-01]
 [ 7.09611083e-01]
 [ 1.05753309e+00]
 [ 5.61252598e-01]
 [ 2.04850374e+00]
 [-1.90206807e+00]
 [ 5.14834217e-01]
 [-9.27441864e-01]
 [ 9.78722030e-01]
 [-1.69588035e+00]
 [-3.32683248e-02]
 [ 3.13185863e-01]
 [-2.33226068e-01]
 [ 9.08076498e-01]
 [-1.55983255e+00]
 [ 1.40444388e+00]
 [ 5.43945944e-01]
 [-5.90338209e-01]
 [-3.83620372e-01]
 [-1.16741658e+00]
 [ 1.55633052e+00]
 [-1.89335905e+00]
 [ 6.78044816e-01]
 [ 6.26815271e-01]
 [-2.79755842e-01]
 [-1.36796682e+00]
 [-5.52974060e-01]
 [-1.01853533e-01]
 [-1.50612396e+00]
 [ 2.34423808e-01]
 [-7.15197942e-01]
 [-1.13017097e-01]
 [-4.34738523e-01]
 [-2.58279533e-01]
 [ 8.70342637e-01]
 [-1.46470155e+00]
 [-1.69230319e+00]
 [-6.07299655e-01]
 [-3.39126416e-01]
 [ 7.52107100e-01]
 [-8.79391274e-02]
 [ 1.15421881e+00]
 [ 7.02481276e-01]
 [-9.85801216e-01]
 [ 1.93139082e+00]
 [ 1.96923608e+00]
 [-3.88665351e-01]
 [-3.99483707e-01]
 [ 1.49132246e+00]
 [ 2.30341042e-01]
 [ 1.23914846e+00]
 [-1.68835020e-01]
 [ 7.81748943e-01]
 [ 9.76180601e-01]
 [-1.72510347e+00]
 [-1.15471637e-01]
 [-5.02337015e-01]
 [-7.90888452e-01]
 [ 6.30367922e-01]
 [-9.51508612e-01]
 [-3.02909387e-01]
 [-1.27893715e-01]
 [ 8.27846620e-01]
 [-1.16741658e+00]
 [ 1.71932680e-01]
 [-3.41260253e-01]
 [-1.83449408e+00]
 [ 1.51924194e-01]
 [ 3.33434496e-02]
 [ 1.29285705e+00]
 [-1.69794067e+00]
 [ 6.75318479e-01]
 [ 3.55681880e-01]
 [ 7.97863347e-02]
 [-1.77544044e-01]
 [ 3.00394073e-01]
 [-7.64848270e-01]
 [ 1.85815485e+00]
 [ 2.64016641e-01]
 [ 4.91754186e-01]
 [-7.35095034e-01]
 [ 7.11239310e-01]
 [-1.72690912e-02]
 [-1.31169230e+00]
 [ 9.41999390e-01]
 [-5.86785558e-01]
 [ 1.52107570e+00]
 [-1.33012157e+00]
 [ 9.66460355e-01]
 [-1.29117820e+00]
 [-1.58016664e-01]
 [-1.92407449e+00]
 [-1.36748572e+00]
 [ 1.89760383e+00]
 [ 3.67832161e-01]
 [ 1.05652187e+00]
 [ 1.59885104e+00]
 [-6.79943125e-01]
 [ 1.84279713e+00]
 [ 6.11938653e-01]
 [-8.88585387e-01]
 [ 6.53447953e-01]
 [-1.06667260e+00]
 [-4.92553180e-04]
 [-4.93122380e-01]
 [ 1.37689085e-01]
 [-1.47132574e+00]
 [-2.86453552e-01]
 [-8.42006604e-01]
 [ 1.41918460e+00]
 [-4.64035158e-01]
 [ 1.63720190e+00]
 [ 6.60602264e-01]
 [-1.26107976e+00]
 [ 7.15754173e-01]
 [ 2.19277946e+00]
 [ 1.65870272e+00]
 [-1.07527023e+00]
 [ 2.55283113e-01]
 [-1.73679715e+00]
 [-1.06101062e+00]
 [-5.59141655e-01]
 [ 1.83617293e+00]
 [-6.51152101e-01]
 [ 1.51344028e+00]
 [-2.82370785e-01]
 [-3.23312090e-01]
 [ 4.93333403e-01]
 [-5.39220058e-01]
 [ 1.37530765e+00]
 [ 9.94104259e-01]
 [ 3.57655315e-01]
 [-1.45083615e+00]
 [-8.02076521e-01]
 [ 8.43709955e-01]
 [-8.25686667e-01]
 [ 2.89711616e-01]
 [-9.22853487e-01]
 [ 3.95525074e-01]
 [-3.91736895e-01]
 [-7.16690270e-01]
 [ 1.36043103e+00]
 [ 8.66789986e-01]
 [ 9.63869917e-01]
 [-1.19348127e+00]
 [ 4.78481290e-01]
 [-7.72434678e-01]
 [-2.41478490e-01]
 [ 9.75780783e-03]
 [-6.06682650e-01]
 [ 8.21222424e-01]
 [-6.41937467e-01]
 [-5.13525083e-01]
 [-1.44262661e-01]
 [ 1.99144487e-01]
 [-2.96260687e-01]
 [-1.20787678e+00]
 [ 3.22375993e-01]
 [ 1.36352708e+00]
 [ 1.16086751e+00]
 [-9.66866337e-01]
 [ 5.05964790e-01]
 [-2.57292816e-01]
 [-4.33295205e-01]
 [ 2.18992570e-01]
 [-1.28971038e+00]
 [ 4.27338634e-01]
 [ 6.67201955e-01]
 [-1.00249811e-01]
 [ 1.34360549e+00]
 [ 1.93139082e+00]
 [ 5.51581362e-01]
 [ 9.17427031e-01]
 [-1.94656203e+00]
 [-1.55822883e+00]
 [ 1.27135623e+00]
 [-1.32042583e+00]
 [ 5.56120730e-01]
 [ 1.03758699e+00]
 [ 4.38551207e-01]
 [ 3.20291165e-01]
 [-6.19955547e-01]
 [-1.45438880e+00]
 [-4.43977663e-01]
 [ 1.55582491e+00]
 [ 1.34656564e+00]
 [-1.74451945e+00]
 [-4.25684292e-01]
 [-5.62669801e-01]
 [-1.50561835e+00]
 [ 4.75249342e-01]
 [-1.15673412e+00]
 [-2.01018292e-01]
 [-6.83976882e-01]
 [-6.31230504e-01]
 [ 3.68449166e-01]
 [ 1.23917296e+00]
 [-9.68470058e-01]
 [ 4.72794802e-01]
 [-7.57125964e-01]
 [-3.55519867e-01]
 [ 1.72419188e+00]
 [-6.11357917e-01]
 [-9.91271960e-02]
 [ 5.72465171e-01]
 [-5.71884435e-01]
 [ 1.78145312e+00]
 [ 1.83516171e+00]
 [ 1.40751543e+00]
 [ 1.84748975e-01]
 [-9.29526692e-01]
 [ 1.06415729e+00]
 [-3.94919834e-01]
 [-7.31517878e-01]
 [-1.40166693e+00]
 [-1.70053111e+00]
 [-1.36393307e+00]
 [ 4.85105486e-01]
 [-3.97510273e-01]
 [-8.60941484e-01]
 [-1.76700699e+00]
 [ 2.23580947e-01]
 [-1.42931083e+00]
 [-1.34598490e+00]
 [-1.26660584e+00]
 [-2.40972879e-01]
 [ 1.22330963e+00]
 [-4.22957955e-01]
 [ 1.54207090e+00]
 [-1.11987558e+00]
 [ 1.07385303e+00]
 [-1.12748650e+00]]

In [31]:

lda_df = pd.DataFrame(lda_result, columns=['LD1'])

lda_df.head()

        LD1
0 -1.004206
1 -1.411499
2  0.541861
3 -0.267519
4 -0.454315